### ISSUE TITLE
Pin layout for Arduino UNO

### ISSUE THREAD

**Issue by chriamue** [budryerson/TFLuna-I2C#2]
Hi, thank you for providing this nice library.
I have some problems connecting the device correctly to my Arduino UNO (R3).
Serial output is always like:
```sh
Status: I2C-WRITEStatus: I2C-WRITEStatus: I2C-WRITEStatus: I2C-WRITEStatus: I2C-WRITE
```
I connected Luna to UNO like:

* 1 -> 5V
* 2 -> GPIO18/SDA
* 3 -> GPIO19/SCL
* 4 -> GND
* 5 -> GND
* 6 -> UNCONNECTED

Can you give little support how to connect please.

Many thanks in advance.

**Comment by budryerson** [comment]
Hey Christian!
Your connections seem to be okay.  Will you please send me all the code your using, a text file of your serial output and, if you can, some pictures of your setup.
I'm sure this is something we can figure out.
Bud Ryerson
San Francisco

**Comment by chriamue** [comment]
Hi, thank you for your reply.
Could make it working switching GPIO18 and GPIO19 some times.
Maybe a loose connection was the problem.

I used this example [script](https://github.com/budryerson/TFLuna-I2C/blob/master/example/TFLI2C_simple.ino).
Here is the setup ![Arduino Setup](https://github.com/chriamue/esp32_ultrasonic/blob/main/arduino_lidar.jpg?raw=true)

Works on
[ESP32](https://github.com/chriamue/esp32_ultrasonic/blob/main/lidar.jpg) too!

**Comment by budryerson** [comment]
Did you try the other I2C pins?

**Comment by Shetyep** [comment]
> Hi, thank you for your reply.
> Could make it working switching GPIO18 and GPIO19 sometimes.
> Maybe a loose connection was the problem.
> 
> I used this example [script](https://github.com/budryerson/TFLuna-I2C/blob/master/example/TFLI2C_simple.ino).
> Here is the setup ![Arduino Setup](https://github.com/chriamue/esp32_ultrasonic/blob/main/arduino_lidar.jpg?raw=true)
> 
> Works on
> [ESP32](https://github.com/chriamue/esp32_ultrasonic/blob/main/lidar.jpg) too!

Can you please provide me code for esp32 and tf luna because this code seems not to be worked? I am not being able to get a proper output out of this. A recurring sentence is been displayed on the serial monitor. I have done the same connections on the ESP32 board which you mentioned above. (total5pins)[5V, G18, G19, GND, GND]
Chriamue bro you mentioned it works on esp32 too. But it seems not working on it. Can you please tell me how you have done on your esp32 and tf luna if possible and give me the solution for it? 
I just want the distance reading appearing on my screen (Serial monitor)

Thank You!
